# Auto-generated packwiz import script
cd "C:/Users/AS1/AppData/Roaming/PrismLauncher/instances/GoToSky Base/modpack"
packwiz curseforge add "https://www.curseforge.com/minecraft/mc-mods/netherportalfix" -y
packwiz curseforge add "https://www.curseforge.com/minecraft/mc-mods/sodium" -y
packwiz curseforge add "https://www.curseforge.com/minecraft/mc-mods/create-optical" -y
packwiz curseforge add "https://www.curseforge.com/minecraft/mc-mods/craterlib" -y
packwiz curseforge add "https://www.curseforge.com/minecraft/mc-mods/cherished-worlds" -y
packwiz curseforge add "https://www.curseforge.com/minecraft/mc-mods/easy-anvils" -y
packwiz curseforge add "https://www.curseforge.com/minecraft/mc-mods/create-totem-factory" -y
packwiz curseforge add "https://www.curseforge.com/minecraft/mc-mods/connectivity" -y
packwiz curseforge add "https://www.curseforge.com/minecraft/mc-mods/create-cafe" -y
packwiz curseforge add "https://www.curseforge.com/minecraft/mc-mods/create-train-parts" -y
packwiz curseforge add "https://www.curseforge.com/minecraft/mc-mods/integrated-stronghold" -y
packwiz curseforge add "https://www.curseforge.com/minecraft/mc-mods/geckolib" -y
packwiz curseforge add "https://www.curseforge.com/minecraft/mc-mods/controlling" -y
packwiz curseforge add "https://www.curseforge.com/minecraft/mc-mods/configured-defaults" -y
packwiz curseforge add "https://www.curseforge.com/minecraft/mc-mods/create-design-n-decor" -y
packwiz curseforge add "https://www.curseforge.com/minecraft/mc-mods/ftb-library-forge" -y
packwiz curseforge add "https://www.curseforge.com/minecraft/mc-mods/create-rubberworks" -y
packwiz curseforge add "https://www.curseforge.com/minecraft/mc-mods/gears-n-kinetics" -y
packwiz curseforge add "https://www.curseforge.com/minecraft/texture-packs/create-chocolate-fountain-zh-hk-translation" -y
packwiz curseforge add "https://www.curseforge.com/minecraft/mc-mods/bellsandwhistles" -y
packwiz curseforge add "https://www.curseforge.com/minecraft/data-packs/create-create-dreams-n-desires-no-diamond-recipe" -y
packwiz curseforge add "https://www.curseforge.com/minecraft/mc-mods/justenoughbreeding" -y
packwiz curseforge add "https://www.curseforge.com/minecraft/mc-mods/euphoria-patches" -y
packwiz curseforge add "https://www.curseforge.com/minecraft/mc-mods/hypertubes" -y
packwiz curseforge add "https://www.curseforge.com/minecraft/mc-mods/drippy-loading-screen" -y
packwiz curseforge add "https://www.curseforge.com/minecraft/texture-packs/create-style-hopper" -y
packwiz curseforge add "https://www.curseforge.com/minecraft/mc-mods/ftb-teams-forge" -y
packwiz curseforge add "https://www.curseforge.com/minecraft/texture-packs/create-slice-dice-zh-hk-translation" -y
packwiz curseforge add "https://www.curseforge.com/minecraft/mc-mods/better-compatibility-checker" -y
packwiz curseforge add "https://www.curseforge.com/minecraft/mc-mods/forgified-fabric-api" -y
packwiz curseforge add "https://www.curseforge.com/minecraft/mc-mods/patchouli" -y
packwiz curseforge add "https://www.curseforge.com/minecraft/mc-mods/industrialized-architecture" -y
packwiz curseforge add "https://www.curseforge.com/minecraft/mc-mods/item-highlighter" -y
packwiz curseforge add "https://www.curseforge.com/minecraft/texture-packs/create-immersive-aircrafts-resource-pack" -y
packwiz curseforge add "https://www.curseforge.com/minecraft/mc-mods/create-wrapped" -y
packwiz curseforge add "https://www.curseforge.com/minecraft/mc-mods/boat-item-view-forge" -y
packwiz curseforge add "https://www.curseforge.com/minecraft/data-packs/create-charcoal-bulk-haunting" -y
packwiz curseforge add "https://www.curseforge.com/minecraft/mc-mods/personality" -y
packwiz curseforge add "https://www.curseforge.com/minecraft/mc-mods/immediatelyfast" -y
packwiz curseforge add "https://www.curseforge.com/minecraft/mc-mods/polymorph" -y
packwiz curseforge add "https://www.curseforge.com/minecraft/mc-mods/create-more-package-couriers" -y
packwiz curseforge add "https://www.curseforge.com/minecraft/mc-mods/sinytra-connector" -y
packwiz curseforge add "https://www.curseforge.com/minecraft/mc-mods/curios" -y
packwiz curseforge add "https://www.curseforge.com/minecraft/data-packs/create-easy-stone-generators-no-obsidian-gen" -y
packwiz curseforge add "https://www.curseforge.com/minecraft/texture-packs/tradingpostzhhktranslation" -y
packwiz curseforge add "https://www.curseforge.com/minecraft/mc-mods/create-fantasizing-again" -y
packwiz curseforge add "https://www.curseforge.com/minecraft/mc-mods/create-new-age" -y
packwiz curseforge add "https://www.curseforge.com/minecraft/mc-mods/create-garnished-reworked" -y
packwiz curseforge add "https://www.curseforge.com/minecraft/mc-mods/handcrafted" -y
packwiz curseforge add "https://www.curseforge.com/minecraft/mc-mods/create-central-kitchen" -y
packwiz curseforge add "https://www.curseforge.com/minecraft/mc-mods/smooth-chunk-save" -y
packwiz curseforge add "https://www.curseforge.com/minecraft/shaders/complementary-reimagined" -y
packwiz curseforge add "https://www.curseforge.com/minecraft/mc-mods/create-confectionery" -y
packwiz curseforge add "https://www.curseforge.com/minecraft/texture-packs/create-quests" -y
packwiz curseforge add "https://www.curseforge.com/minecraft/mc-mods/server-browser" -y
packwiz curseforge add "https://www.curseforge.com/minecraft/mc-mods/melody" -y
packwiz curseforge add "https://www.curseforge.com/minecraft/mc-mods/puzzles-lib" -y
packwiz curseforge add "https://www.curseforge.com/minecraft/mc-mods/power-grid" -y
packwiz curseforge add "https://www.curseforge.com/minecraft/mc-mods/integrated-api" -y
packwiz curseforge add "https://www.curseforge.com/minecraft/mc-mods/trading-post" -y
packwiz curseforge add "https://www.curseforge.com/minecraft/mc-mods/irisshaders" -y
packwiz curseforge add "https://www.curseforge.com/minecraft/mc-mods/create-blocks-bogies" -y
packwiz curseforge add "https://www.curseforge.com/minecraft/mc-mods/create-transmission" -y
packwiz curseforge add "https://www.curseforge.com/minecraft/mc-mods/appleskin" -y
packwiz curseforge add "https://www.curseforge.com/minecraft/texture-packs/createquestingunofficialzhhktranslation" -y
packwiz curseforge add "https://www.curseforge.com/minecraft/mc-mods/chat-heads" -y
packwiz curseforge add "https://www.curseforge.com/minecraft/mc-mods/cut-through" -y
packwiz curseforge add "https://www.curseforge.com/minecraft/mc-mods/does-it-tick" -y
packwiz curseforge add "https://www.curseforge.com/minecraft/mc-mods/amendments" -y
packwiz curseforge add "https://www.curseforge.com/minecraft/mc-mods/continuity" -y
packwiz curseforge add "https://www.curseforge.com/minecraft/mc-mods/create-diesel-generators" -y
packwiz curseforge add "https://www.curseforge.com/minecraft/texture-packs/c-u-3d-wrench-model" -y
packwiz curseforge add "https://www.curseforge.com/minecraft/mc-mods/create-integrated-farming" -y
packwiz curseforge add "https://www.curseforge.com/minecraft/mc-mods/create-better-fps" -y
packwiz curseforge add "https://www.curseforge.com/minecraft/mc-mods/create-schematicchecker" -y
packwiz curseforge add "https://www.curseforge.com/minecraft/mc-mods/ftb-filter-system" -y
packwiz curseforge add "https://www.curseforge.com/minecraft/mc-mods/prickle" -y
packwiz curseforge add "https://www.curseforge.com/minecraft/mc-mods/corpse" -y
packwiz curseforge add "https://www.curseforge.com/minecraft/mc-mods/easy-magic" -y
packwiz curseforge add "https://www.curseforge.com/minecraft/mc-mods/create-connected" -y
packwiz curseforge add "https://www.curseforge.com/minecraft/mc-mods/idas" -y
packwiz curseforge add "https://www.curseforge.com/minecraft/mc-mods/no-chat-reports" -y
packwiz curseforge add "https://www.curseforge.com/minecraft/mc-mods/create-encased" -y
packwiz curseforge add "https://www.curseforge.com/minecraft/mc-mods/leaves-be-gone" -y
packwiz curseforge add "https://www.curseforge.com/minecraft/mc-mods/enchantment-descriptions" -y
packwiz curseforge add "https://www.curseforge.com/minecraft/mc-mods/create-stuff-additions" -y
packwiz curseforge add "https://www.curseforge.com/minecraft/mc-mods/skin-layers-3d" -y
packwiz curseforge add "https://www.curseforge.com/minecraft/mc-mods/boatload" -y
packwiz curseforge add "https://www.curseforge.com/minecraft/mc-mods/visual-workbench" -y
packwiz curseforge add "https://www.curseforge.com/minecraft/mc-mods/ftb-quests-forge" -y
packwiz curseforge add "https://www.curseforge.com/minecraft/mc-mods/integrated-villages" -y
packwiz curseforge add "https://www.curseforge.com/minecraft/mc-mods/terrablender-neoforge" -y
packwiz curseforge add "https://www.curseforge.com/minecraft/texture-packs/stay-true" -y
packwiz curseforge add "https://www.curseforge.com/minecraft/mc-mods/create-mechanical-confection" -y
packwiz curseforge add "https://www.curseforge.com/minecraft/mc-mods/create-metalwork" -y
packwiz curseforge add "https://www.curseforge.com/minecraft/mc-mods/entity-model-features" -y
packwiz curseforge add "https://www.curseforge.com/minecraft/mc-mods/just-enough-resources-jer" -y
packwiz curseforge add "https://www.curseforge.com/minecraft/mc-mods/create-bits-n-bobs" -y
packwiz curseforge add "https://www.curseforge.com/minecraft/data-packs/all-of-create-data" -y
packwiz curseforge add "https://www.curseforge.com/minecraft/texture-packs/create-vibrant-vaults-zh-hk-translation" -y
packwiz curseforge add "https://www.curseforge.com/minecraft/mc-mods/architectury-api" -y
packwiz curseforge add "https://www.curseforge.com/minecraft/mc-mods/create-winery" -y
packwiz curseforge add "https://www.curseforge.com/minecraft/mc-mods/konkrete" -y
packwiz curseforge add "https://www.curseforge.com/minecraft/mc-mods/client-crafting" -y
packwiz curseforge add "https://www.curseforge.com/minecraft/mc-mods/packet-fixer" -y
packwiz curseforge add "https://www.curseforge.com/minecraft/mc-mods/create-mob-spawners" -y
packwiz curseforge add "https://www.curseforge.com/minecraft/mc-mods/reeses-sodium-options" -y
packwiz curseforge add "https://www.curseforge.com/minecraft/mc-mods/crash-assistant" -y
packwiz curseforge add "https://www.curseforge.com/minecraft/mc-mods/smarter-farmers-farmers-replant" -y
packwiz curseforge add "https://www.curseforge.com/minecraft/texture-packs/gui-retextures" -y
packwiz curseforge add "https://www.curseforge.com/minecraft/mc-mods/create-blaze-burner-fuels" -y
packwiz curseforge add "https://www.curseforge.com/minecraft/texture-packs/create-ui" -y
packwiz curseforge add "https://www.curseforge.com/minecraft/mc-mods/cupboard" -y
packwiz curseforge add "https://www.curseforge.com/minecraft/mc-mods/toast-control" -y
packwiz curseforge add "https://www.curseforge.com/minecraft/data-packs/create-no-silverfish-xp-farm" -y
packwiz curseforge add "https://www.curseforge.com/minecraft/mc-mods/create-dragons-plus" -y
packwiz curseforge add "https://www.curseforge.com/minecraft/texture-packs/create-transmission-zh-hk-translation" -y
packwiz curseforge add "https://www.curseforge.com/minecraft/mc-mods/paxi-neoforge" -y
packwiz curseforge add "https://www.curseforge.com/minecraft/mc-mods/blueprint" -y
packwiz curseforge add "https://www.curseforge.com/minecraft/mc-mods/create-escalated" -y
packwiz curseforge add "https://www.curseforge.com/minecraft/mc-mods/chunk-sending-forge-fabric" -y
packwiz curseforge add "https://www.curseforge.com/minecraft/mc-mods/structure-essentials-forge-fabric" -y
packwiz curseforge add "https://www.curseforge.com/minecraft/mc-mods/just-enough-professions-jep" -y
packwiz curseforge add "https://www.curseforge.com/minecraft/mc-mods/create" -y
packwiz curseforge add "https://www.curseforge.com/minecraft/mc-mods/supplementaries" -y
packwiz curseforge add "https://www.curseforge.com/minecraft/mc-mods/iceberg" -y
packwiz curseforge add "https://www.curseforge.com/minecraft/mc-mods/create-railways-navigator" -y
packwiz curseforge add "https://www.curseforge.com/minecraft/mc-mods/yungs-api-neoforge" -y
packwiz curseforge add "https://www.curseforge.com/minecraft/mc-mods/slice-and-dice" -y
packwiz curseforge add "https://www.curseforge.com/minecraft/mc-mods/selene" -y
packwiz curseforge add "https://www.curseforge.com/minecraft/mc-mods/create-misc-and-things" -y
packwiz curseforge add "https://www.curseforge.com/minecraft/mc-mods/neruina" -y
packwiz curseforge add "https://www.curseforge.com/minecraft/mc-mods/lmft" -y
packwiz curseforge add "https://www.curseforge.com/minecraft/mc-mods/farmers-delight" -y
packwiz curseforge add "https://www.curseforge.com/minecraft/texture-packs/create-trading-floor-zh-hk-translation" -y
packwiz curseforge add "https://www.curseforge.com/minecraft/mc-mods/create-ornithopter-glider" -y
packwiz curseforge add "https://www.curseforge.com/minecraft/mc-mods/alltheleaks" -y
packwiz curseforge add "https://www.curseforge.com/minecraft/texture-packs/create-immersive-aircrafts-data-pack" -y
packwiz curseforge add "https://www.curseforge.com/minecraft/texture-packs/create-advancement-plagues" -y
packwiz curseforge add "https://www.curseforge.com/minecraft/mc-mods/coroutil" -y
packwiz curseforge add "https://www.curseforge.com/minecraft/mc-mods/dynamiclights-reforged" -y
packwiz curseforge add "https://www.curseforge.com/minecraft/mc-mods/resourceful-lib" -y
packwiz curseforge add "https://www.curseforge.com/minecraft/mc-mods/mouse-tweaks" -y
packwiz curseforge add "https://www.curseforge.com/minecraft/mc-mods/create-factory" -y
packwiz curseforge add "https://www.curseforge.com/minecraft/texture-packs/create-touch-ups" -y
packwiz curseforge add "https://www.curseforge.com/minecraft/mc-mods/open-parties-and-claims-pvp-support" -y
packwiz curseforge add "https://www.curseforge.com/minecraft/mc-mods/create-dreams-desires" -y
packwiz curseforge add "https://www.curseforge.com/minecraft/texture-packs/boatload-zh-hk-translation" -y
packwiz curseforge add "https://www.curseforge.com/minecraft/texture-packs/create-stuff-n-additions-zh-hk-translation" -y
packwiz curseforge add "https://www.curseforge.com/minecraft/mc-mods/bisecthosting-server-integration-menu-neoforge" -y
packwiz curseforge add "https://www.curseforge.com/minecraft/texture-packs/create-pattern-schematics-zh-hk-translation" -y
packwiz curseforge add "https://www.curseforge.com/minecraft/mc-mods/create-pattern-schematics" -y
packwiz curseforge add "https://www.curseforge.com/minecraft/mc-mods/createaddition" -y
packwiz curseforge add "https://www.curseforge.com/minecraft/mc-mods/create-deep-dark" -y
packwiz curseforge add "https://www.curseforge.com/minecraft/mc-mods/recipe-essentials-forge-fabric" -y
packwiz curseforge add "https://www.curseforge.com/minecraft/mc-mods/fix-gpu-memory-leak" -y
packwiz curseforge add "https://www.curseforge.com/minecraft/mc-mods/create-enchantment-industry" -y
packwiz curseforge add "https://www.curseforge.com/minecraft/mc-mods/sodium-options-api" -y
packwiz curseforge add "https://www.curseforge.com/minecraft/mc-mods/collective" -y
packwiz curseforge add "https://www.curseforge.com/minecraft/mc-mods/create-mobile-packages" -y
packwiz curseforge add "https://www.curseforge.com/minecraft/mc-mods/simple-discord-rpc" -y
packwiz curseforge add "https://www.curseforge.com/minecraft/texture-packs/createaddonsfix" -y
packwiz curseforge add "https://www.curseforge.com/minecraft/mc-mods/jade" -y
packwiz curseforge add "https://www.curseforge.com/minecraft/mc-mods/create-framed" -y
packwiz curseforge add "https://www.curseforge.com/minecraft/texture-packs/idas-unofficialzhhktranslation" -y
packwiz curseforge add "https://www.curseforge.com/minecraft/mc-mods/copycats" -y
packwiz curseforge add "https://www.curseforge.com/minecraft/texture-packs/handcraftedunofficialzhhktranslation" -y
packwiz curseforge add "https://www.curseforge.com/minecraft/mc-mods/backpacked" -y
packwiz curseforge add "https://www.curseforge.com/minecraft/mc-mods/sodium-leaf-culling" -y
packwiz curseforge add "https://www.curseforge.com/minecraft/mc-mods/gallery" -y
packwiz curseforge add "https://www.curseforge.com/minecraft/mc-mods/lithium" -y
packwiz curseforge add "https://www.curseforge.com/minecraft/mc-mods/modernfix" -y
packwiz curseforge add "https://www.curseforge.com/minecraft/mc-mods/create-copper-splashing" -y
packwiz curseforge add "https://www.curseforge.com/minecraft/shaders/complementary-unbound" -y
packwiz curseforge add "https://www.curseforge.com/minecraft/texture-packs/create-train-parts-zh-hk-translation" -y
packwiz curseforge add "https://www.curseforge.com/minecraft/mc-mods/chunk-activity-tracker" -y
packwiz curseforge add "https://www.curseforge.com/minecraft/mc-mods/lithostitched" -y
packwiz curseforge add "https://www.curseforge.com/minecraft/mc-mods/leaky" -y
packwiz curseforge add "https://www.curseforge.com/minecraft/mc-mods/create-prismatic-shine" -y
packwiz curseforge add "https://www.curseforge.com/minecraft/mc-mods/jei" -y
packwiz curseforge add "https://www.curseforge.com/minecraft/mc-mods/quark" -y
packwiz curseforge add "https://www.curseforge.com/minecraft/mc-mods/luna" -y
packwiz curseforge add "https://www.curseforge.com/minecraft/mc-mods/despawn-tweaks" -y
packwiz curseforge add "https://www.curseforge.com/minecraft/mc-mods/aoc-core" -y
packwiz curseforge add "https://www.curseforge.com/minecraft/mc-mods/zeta" -y
packwiz curseforge add "https://www.curseforge.com/minecraft/mc-mods/create-mechanical-botany" -y
packwiz curseforge add "https://www.curseforge.com/minecraft/mc-mods/create-trading-floor" -y
packwiz curseforge add "https://www.curseforge.com/minecraft/mc-mods/what-are-they-up-to" -y
packwiz curseforge add "https://www.curseforge.com/minecraft/mc-mods/txnilib" -y
packwiz curseforge add "https://www.curseforge.com/minecraft/mc-mods/necronomicon" -y
packwiz curseforge add "https://www.curseforge.com/minecraft/texture-packs/create-more-package-couriers-zh-hk-translation" -y
packwiz curseforge add "https://www.curseforge.com/minecraft/mc-mods/open-parties-and-claims" -y
packwiz curseforge add "https://www.curseforge.com/minecraft/mc-mods/fancymenu" -y
packwiz curseforge add "https://www.curseforge.com/minecraft/mc-mods/create-stone-generators" -y
packwiz curseforge add "https://www.curseforge.com/minecraft/mc-mods/bad-wither-no-cookie-reloaded" -y
packwiz curseforge add "https://www.curseforge.com/minecraft/mc-mods/caelus" -y
packwiz curseforge add "https://www.curseforge.com/minecraft/mc-mods/ftb-xmod-compat" -y
packwiz curseforge add "https://www.curseforge.com/minecraft/mc-mods/placebo" -y
packwiz curseforge add "https://www.curseforge.com/minecraft/mc-mods/pick-up-notifier" -y
packwiz curseforge add "https://www.curseforge.com/minecraft/mc-mods/epherolib" -y
packwiz curseforge add "https://www.curseforge.com/minecraft/mc-mods/biome-music" -y
packwiz curseforge add "https://www.curseforge.com/minecraft/mc-mods/create-fast-schematiccannon" -y
packwiz curseforge add "https://www.curseforge.com/minecraft/mc-mods/balm" -y
packwiz curseforge add "https://www.curseforge.com/minecraft/mc-mods/redirected" -y
packwiz curseforge add "https://www.curseforge.com/minecraft/mc-mods/create-sound-of-steam" -y
packwiz curseforge add "https://www.curseforge.com/minecraft/mc-mods/tradeworks" -y
packwiz curseforge add "https://www.curseforge.com/minecraft/mc-mods/create-aquatic-ambitions" -y
packwiz curseforge add "https://www.curseforge.com/minecraft/mc-mods/kotlin-for-forge" -y
packwiz curseforge add "https://www.curseforge.com/minecraft/texture-packs/all-of-create-core" -y
packwiz curseforge add "https://www.curseforge.com/minecraft/mc-mods/extra-create-recipe" -y
packwiz curseforge add "https://www.curseforge.com/minecraft/mc-mods/ferritecore" -y
packwiz curseforge add "https://www.curseforge.com/minecraft/mc-mods/alternate-current" -y
packwiz curseforge add "https://www.curseforge.com/minecraft/mc-mods/clumps" -y
packwiz curseforge add "https://www.curseforge.com/minecraft/mc-mods/xaeros-minimap" -y
packwiz curseforge add "https://www.curseforge.com/minecraft/mc-mods/create-chocolate-fountain" -y
packwiz curseforge add "https://www.curseforge.com/minecraft/mc-mods/bookshelf" -y
packwiz curseforge add "https://www.curseforge.com/minecraft/mc-mods/framework" -y
packwiz curseforge add "https://www.curseforge.com/minecraft/mc-mods/loot-integrations" -y
packwiz curseforge add "https://www.curseforge.com/minecraft/mc-mods/resource-pack-overrides" -y
packwiz curseforge add "https://www.curseforge.com/minecraft/mc-mods/magnesium-extras" -y
packwiz curseforge add "https://www.curseforge.com/minecraft/mc-mods/searchables" -y
packwiz curseforge add "https://www.curseforge.com/minecraft/mc-mods/xaeros-world-map" -y
packwiz curseforge add "https://www.curseforge.com/minecraft/mc-mods/entity-texture-features-fabric" -y
packwiz curseforge add "https://www.curseforge.com/minecraft/texture-packs/createtweakedcontrollerunofficialzhhk" -y
packwiz curseforge add "https://www.curseforge.com/minecraft/mc-mods/some-assembly-required" -y
packwiz curseforge add "https://www.curseforge.com/minecraft/mc-mods/not-enough-animations" -y
packwiz curseforge add "https://www.curseforge.com/minecraft/texture-packs/create-blaze-burner-fuels-zh-hk-translation" -y
packwiz curseforge add "https://www.curseforge.com/minecraft/mc-mods/create-vibrant-vaults" -y
packwiz curseforge add "https://www.curseforge.com/minecraft/mc-mods/immersive-aircraft" -y
packwiz curseforge add "https://www.curseforge.com/minecraft/mc-mods/item-obliterator" -y
packwiz curseforge add "https://www.curseforge.com/minecraft/mc-mods/create-food" -y
