name = "GoToSky!"
author = "AS1AW"
version = "1.0.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1248ec2471594a0dd497287493988fbd52f67082830a397db15a45fda0e7f89a"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.221"
