name = "GoToSky!"
author = "AS1AW"
version = "1.0.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4550b90028ddb2af4113383941a5ffecd48ff8b657695172c6feabacb5593de5"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.221"
